### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by OutiSig** [libbitcoin/libbitcoin-server#562] opened 2023-02-15 14:47 UTC
There is a error when bulding the libbitcoin version3 on debian stable (bullseye, buster, stretch). 

I install all dependencies: `build-essential autoconf automake libtool pkg-config git wget make cmake gcc g++`

But get the same `install.sh` error when try to build libbitcoin-server (and also libbitcoin-expolorer, libbitcoin-protocol) on line `+ shift 4`.

I successfully built this in the last year, but now I got this install.sh error:

##### ./install.sh --build-boost --build-zmq --disable-shared

```
...
********************** Prepairing to build libbitcoin-protocol **********************
+ printf '\n********************** %s **********************\n' 'Prepairing to build libbitcoin-protocol'
+ make_project_directory libbitcoin-protocol 3 false --without-tests --without-examples --with-boost=/usr/local --with-pkgconfigdir=/usr/local/lib/pkgconfig '' '' --disable-shared --enable-static --prefix=/usr/local
+ local PROJ_NAME=libbitcoin-protocol
+ local JOBS=3
+ local TEST=false
+ shift 3
+ push_directory libbitcoin-protocol
+ local DIRECTORY=libbitcoin-protocol
+ pushd libbitcoin-protocol
+ local PROJ_CONFIG_DIR
++ pwd
+ PROJ_CONFIG_DIR=/home/bs/build-libbitcoin-server/libbitcoin-protocol
+ ./autogen.sh
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:36: installing 'build-aux/ar-lib'
configure.ac:36: installing 'build-aux/compile'
configure.ac:42: installing 'build-aux/config.guess'
configure.ac:42: installing 'build-aux/config.sub'
configure.ac:30: installing 'build-aux/install-sh'
configure.ac:30: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
configure options:
--without-tests
--without-examples
--with-boost=/usr/local
--with-pkgconfigdir=/usr/local/lib/pkgconfig
--disable-shared
--enable-static
--prefix=/usr/local
+ configure_options --without-tests --without-examples --with-boost=/usr/local --with-pkgconfigdir=/usr/local/lib/pkgconfig '' '' --disable-shared --enable-static --prefix=/usr/local
+ display_message 'configure options:'
+ printf '%s\n' 'configure options:'
+ for OPTION in "$@"
+ [[ -n --without-tests ]]
+ display_message --without-tests
+ printf '%s\n' --without-tests
+ for OPTION in "$@"
+ [[ -n --without-examples ]]
+ display_message --without-examples
+ printf '%s\n' --without-examples
+ for OPTION in "$@"
+ [[ -n --with-boost=/usr/local ]]
+ display_message --with-boost=/usr/local
+ printf '%s\n' --with-boost=/usr/local
+ for OPTION in "$@"
+ [[ -n --with-pkgconfigdir=/usr/local/lib/pkgconfig ]]
+ display_message --with-pkgconfigdir=/usr/local/lib/pkgconfig
+ printf '%s\n' --with-pkgconfigdir=/usr/local/lib/pkgconfig
+ for OPTION in "$@"
+ [[ -n '' ]]
+ for OPTION in "$@"
+ [[ -n '' ]]
+ for OPTION in "$@"
+ [[ -n --disable-shared ]]
+ display_message --disable-shared
+ printf '%s\n' --disable-shared
+ for OPTION in "$@"
+ [[ -n --enable-static ]]
+ display_message --enable-static
+ printf '%s\n' --enable-static
+ for OPTION in "$@"
+ [[ -n --prefix=/usr/local ]]
+ display_message --prefix=/usr/local
+ printf '%s\n' --prefix=/usr/local
+ ./configure --without-tests --without-examples --with-boost=/usr/local --with-pkgconfigdir=/usr/local/lib/pkgconfig '' '' --disable-shared --enable-static --prefix=/usr/local
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: unrecognized options: --without-examples
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking for a sed that does not truncate output... (cached) /bin/sed
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether g++ supports C++11 features with -std=c++11... yes
checking --with-pkgconfigdir option... /usr/local/lib/pkgconfig
checking --with-tests option... no
checking --enable-ndebug option... yes
checking --enable-isystem option... no
checking for boostlib >= 1.72.0 (107200) includes in "/usr/local/include"... yes
checking for boostlib >= 1.72.0 (107200) lib path in "/usr/local/lib/x86_64-linux-gnu"... no
checking for boostlib >= 1.72.0 (107200) lib path in "/usr/local/lib64"... no
checking for boostlib >= 1.72.0 (107200) lib path in "/usr/local/libx32"... no
checking for boostlib >= 1.72.0 (107200) lib path in "/usr/local/lib"... yes
checking for boostlib >= 1.72.0 (107200)... yes
configure: boost_CPPFLAGS : -I/usr/local/include
configure: boost_ISYS_CPPFLAGS : -isystem/usr/local/include
configure: boost_LDFLAGS : -L/usr/local/lib
configure: boost_BUILD_CPPFLAGS : -I/usr/local/include
checking for libzmq >= 4.3.4... yes
configure: zmq_CPPFLAGS : -I/usr/local/include
configure: zmq_ISYS_CPPFLAGS : -isystem/usr/local/include
configure: zmq_OTHER_CFLAGS :
configure: zmq_INCLUDEDIR : /usr/local/include
configure: zmq_LIBS : -L/usr/local/lib -lzmq -lstdc++ -lpthread -lrt
configure: zmq_BUILD_CPPFLAGS : -I/usr/local/include
checking for libbitcoin-system >= 3.7.0... yes
configure: bitcoin_system_CPPFLAGS : -I/usr/local/include
configure: bitcoin_system_ISYS_CPPFLAGS : -isystem/usr/local/include
configure: bitcoin_system_OTHER_CFLAGS :
configure: bitcoin_system_INCLUDEDIR : /usr/local/include
configure: bitcoin_system_LIBS : -L/usr/local/lib -lbitcoin-system -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_locale -lboost_log -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lrt -ldl -lsecp256k1
configure: bitcoin_system_BUILD_CPPFLAGS : -I/usr/local/include
checking whether C++ compiler accepts -std=c++11... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -Wall... (cached) yes
checking whether C++ compiler accepts -Wextra... yes
checking whether C++ compiler accepts -Wextra... (cached) yes
checking whether C++ compiler accepts -Wpedantic... yes
checking whether C++ compiler accepts -Wpedantic... (cached) yes
checking whether C++ compiler accepts -Wno-reorder... yes
checking whether C++ compiler accepts -Wno-missing-field-initializers... yes
checking whether C++ compiler accepts -Wno-missing-braces... yes
checking whether C++ compiler accepts -Wno-comment... yes
checking whether C++ compiler accepts -Wno-deprecated-copy... yes
checking whether the linker accepts -fstack-protector... yes
checking whether the linker accepts -fstack-protector-all... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin-protocol.pc
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --without-examples
+ make_jobs 3
+ local JOBS=3
+ shift 1
+ VERBOSITY=
+ [[ -n DISPLAY_VERBOSE ]]
+ VERBOSITY=VERBOSE=1
+ SEQUENTIAL=1
+ [[ 3 > 1 ]]
+ make -j3 VERBOSE=1
  CXX      src/libbitcoin_protocol_la-settings.lo
  CXX      src/zmq/libbitcoin_protocol_la-certificate.lo
  CXX      src/zmq/libbitcoin_protocol_la-authenticator.lo
  CXX      src/zmq/libbitcoin_protocol_la-context.lo
  CXX      src/zmq/libbitcoin_protocol_la-frame.lo
  CXX      src/zmq/libbitcoin_protocol_la-identifiers.lo
  CXX      src/zmq/libbitcoin_protocol_la-message.lo
  CXX      src/zmq/libbitcoin_protocol_la-poller.lo
  CXX      src/zmq/libbitcoin_protocol_la-socket.lo
  CXX      src/zmq/libbitcoin_protocol_la-worker.lo
  CXX      src/zmq/libbitcoin_protocol_la-zeromq.lo
  CXXLD    src/libbitcoin-protocol.la
+ [[ false == true ]]
+ make install
make[1]: Entering directory '/home/bs/build-libbitcoin-server/libbitcoin-protocol'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   src/libbitcoin-protocol.la '/usr/local/lib'
libtool: install: /usr/bin/install -c src/.libs/libbitcoin-protocol.lai /usr/local/lib/libbitcoin-protocol.la
libtool: install: /usr/bin/install -c src/.libs/libbitcoin-protocol.a /usr/local/lib/libbitcoin-protocol.a
libtool: install: chmod 644 /usr/local/lib/libbitcoin-protocol.a
libtool: install: ranlib /usr/local/lib/libbitcoin-protocol.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/sbin" ldconfig -n /usr/local/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/share/doc/libbitcoin-protocol'
 /usr/bin/install -c -m 644 AUTHORS COPYING ChangeLog INSTALL NEWS README '/usr/local/share/doc/libbitcoin-protocol'
 /bin/mkdir -p '/usr/local/include/bitcoin'
 /usr/bin/install -c -m 644 include/bitcoin/protocol.hpp '/usr/local/include/bitcoin'
 /bin/mkdir -p '/usr/local/include/bitcoin/protocol'
 /usr/bin/install -c -m 644 include/bitcoin/protocol/define.hpp include/bitcoin/protocol/settings.hpp include/bitcoin/protocol/version.hpp '/usr/local/include/bitcoin/protocol'
 /bin/mkdir -p '/usr/local/include/bitcoin/protocol/zmq'
 /usr/bin/install -c -m 644 include/bitcoin/protocol/zmq/authenticator.hpp include/bitcoin/protocol/zmq/certificate.hpp include/bitcoin/protocol/zmq/context.hpp include/bitcoin/protocol/zmq/frame.hpp include/bitcoin/protocol/zmq/identifiers.hpp include/bitcoin/protocol/zmq/message.hpp include/bitcoin/protocol/zmq/poller.hpp include/bitcoin/protocol/zmq/socket.hpp include/bitcoin/protocol/zmq/worker.hpp include/bitcoin/protocol/zmq/zeromq.hpp '/usr/local/include/bitcoin/protocol/zmq'
 /bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libbitcoin-protocol.pc '/usr/local/lib/pkgconfig'
make[1]: Leaving directory '/home/bs/build-libbitcoin-server/libbitcoin-protocol'
+ configure_links
+ [[ Linux == Linux ]]
+ [[ /usr/local == \/\u\s\r\/\l\o\c\a\l ]]
+ ldconfig
+ pop_directory
+ popd
+ [[ '' == true ]]
+ create_from_github libbitcoin libbitcoin-server version3
+ push_directory ''
+ local DIRECTORY=
+ pushd ''
+ local ACCOUNT=libbitcoin
+ local REPO=libbitcoin-server
+ local BRANCH=version3
+ local BUILD=
+ shift 4

real	12m35.937s
user	28m30.017s
sys	3m3.579s
The command '/bin/bash -eux -c ./install.sh --build-boost --build-zmq --disable-shared' returned a non-zero code: 1

```
How-to solve the error?

**Comment by pmienk** [comment] 2023-02-15 21:20
Thank you for notifying us of this. It was an oversight on my part while juggling the three installation scripts. The issue is fixed via libbitcoin/libbitcoin-server#563 and more generally by libbitcoin/libbitcoin-build#299

**Closed by pmienk** 2023-02-15 21:20 UTC
Labels: build
