### ISSUE TITLE
Connection failure with server certificate.

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-server#168] opened 2016-03-22 14:54 UTC
I've set up the libbitcoin-server with encryption using the wiki instructions, but whenever trying to connect to the server from bx I receive the following error:

```
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
CURVE I: cannot open client INITIATE vouch
```

I'm not using client authentication.

**Comment by evoskuil** [comment] 2016-03-23 05:10
Hey, @hoffmabc - did you figure this one out?

**Comment by hoffmabc** [comment] 2016-03-23 12:11
I'm not really sure why it stopped occurring. It was happening quite a bit and then just stopped. Since I couldn't replicate I closed it.

**Comment by evoskuil** [comment] 2016-03-23 19:48
Okay, thanks for letting us know.

**Comment by evoskuil** [comment] 2016-03-24 21:44
II'm going to keep this open to track the issue.

**Comment by hoffmabc** [comment] 2016-03-24 21:45
Ok if it occurs again I'm going to provide more info.

**Comment by evoskuil** [comment] 2016-04-07 11:24
I'm able to reproduce this with version2 and a current release build of the zmq dependencies, with both client and server in the msvc debugger. All of the parameterization looks correct, so the cause is still eluding me.

**Comment by evoskuil** [comment] 2016-04-08 09:45
# Repro

### Server
```cpp
#include <czmq++/czmqpp.hpp>

int main()
{
    czmqpp::context context;
    czmqpp::socket socket(context, ZMQ_ROUTER);
    assert(socket.self() != nullptr);

    static const auto public_key = "rq:rM>}U?@Lns47E1%kR.o@n%FcmmsL/@{H8]yf7";
    static const auto secret_key = "JTKVSB%%)wK0E.X)V>+}o?pNmC{O&4W4b!Ni{Lh6";

    int as_server = 1;
    zmq_setsockopt(socket.self(), ZMQ_CURVE_SERVER, &as_server, sizeof(int));
    //socket.set_curve_server(as_server);

    zmq_setsockopt(socket.self(), ZMQ_CURVE_PUBLICKEY, public_key, strlen(public_key));
    zmq_setsockopt(socket.self(), ZMQ_CURVE_SECRETKEY, secret_key, strlen(secret_key));
    //czmqpp::certificate certificate("C:\\ProgramData\\libbitcoin\\cert.txt");
    //assert(certificate.valid());
    //certificate.apply(socket);

    auto connected = socket.bind("tcp://*:9091");
    assert(connected == 9091);

    czmqpp::poller poller(socket);
    assert(poller.self() != nullptr);

    czmqpp::socket which = poller.wait(100000);
    assert(which == socket);

    czmqpp::message message;
    message.receive(socket);
}
```

### Client
```cpp
#include <czmq++/czmqpp.hpp>

int main()
{
    czmqpp::context context;
    czmqpp::socket socket(context, ZMQ_DEALER);
    assert(socket.self() != nullptr);

    static const auto public_key = "rq:rM>}U?@Lns47E1%kR.o@n%FcmmsL/@{H8]yf7";
    //static const auto secret_key = "JTKVSB%%)wK0E.X)V>+}o?pNmC{O&4W4b!Ni{Lh6";

    zmq_setsockopt(socket.self(), ZMQ_CURVE_SERVERKEY, public_key, strlen(public_key));
    //socket.set_curve_serverkey(public_key);

    auto connected = socket.connect("tcp://localhost:9091");
    assert(connected == 0);

    czmqpp::message message;

    // "blockchain.fetch_last_height"
    message.append(
    {
        0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69,
        0x6e, 0x2e, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x6c,
        0x61, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68,
        0x74
    });

    // int(1)
    message.append({ 0x01, 0x00, 0x00, 0x00 });

    // data{}
    message.append({});

    auto sent = message.send(socket);
    assert(sent);

    czmqpp::poller poller(socket);
    poller.wait(1000);
}
```

**Comment by evoskuil** [comment] 2016-04-13 21:57
I have some feedback on this from ZeroMQ folks, need some to work through it though.

**Comment by evoskuil** [comment] 2016-05-02 08:20
**libbitcoin-client** is missing the application of `czmqpp::certificate` to the `czmqpp::socket`.

**Comment by evoskuil** [comment] 2016-05-02 08:46
From the looks of the **libbitcoin-client** sources it appears that this would not have been a problem when also using client identity certificates, except for the fact that the lifetime of the certificates was improperly managed, resulting in loss of scope and eventual failure.

**Comment by evoskuil** [comment] 2016-05-02 13:55
Resolved in version2 (pending in master).

**Comment by evoskuil** [comment] 2016-05-03 23:08
The resolution of this may have been too restrictive (in requiring cert usage). Looking into this now.

**Comment by evoskuil** [comment] 2016-05-04 11:51
I've worked up the full matrix of curve scenarios, requirements and error messages for server and client auth.

![image](https://cloud.githubusercontent.com/assets/1369335/15013291/a1243b0c-11b3-11e6-87b3-21746a849fdd.png)

**Comment by evoskuil** [comment] 2016-05-05 11:30
I've resolved the issues in version2 secure connections. There are two configurable values on both server and client. I've tested the full matrix of options with both valid and invalid configuration. Everything works as shown in the matrix above. Once the pull requests are complete I'll port the changes to master.

Note that when using a client identity certificate a server certificate is always required. Also note that when a server certificate is configured the client must provide the server's key.

**Closed by evoskuil** 2016-05-05 11:30 UTC
Labels: bug

**Comment by hoffmabc** [comment] 2016-05-05 11:31
:+1: will test it out

**Comment by evoskuil** [comment] 2016-05-18 10:51
@hoffmabc Once I get external confirmation for this I'm planning to tag v2.5 for release.

**Comment by hoffmabc** [comment] 2016-05-18 10:56
Sorry I will validate this morning. Got distracted.
