### ISSUE TITLE
Infinite loop while syncing blockchain

### ISSUE THREAD

**Issue by swansontec** [libbitcoin/libbitcoin-server#44] opened 2015-02-17 09:30 UTC
The CPU is stuck at 100%, and the server is no longer storing blocks. Restarting the process and rebooting the box do nothing to fix this.

Here is a stack trace of the offending thread (all other threads are asleep in `poll` functions):

```
#0  libbitcoin::chain::htdb_record_list_item<std::array<unsigned char, 20ul> >::next_index (this=this@entry=0x7fffebffdbe0)
    at ./include/bitcoin/blockchain/impl/htdb_record_list_item.ipp:101
#1  0x00007ffff72688b8 in libbitcoin::chain::htdb_record<std::array<unsigned char, 20ul> >::get (this=0x7fffffffe1c0, key=...)
    at ./include/bitcoin/blockchain/impl/htdb_record.ipp:62
#2  0x00007ffff7268be2 in libbitcoin::chain::multimap_records<std::array<unsigned char, 20ul> >::add_row(std::array<unsigned char, 20ul> const&, std::function<void (unsigned char*)>) (this=this@entry=0x7fffffffe210, key=..., write=...)
    at ./include/bitcoin/blockchain/impl/multimap_records.ipp:47
#3  0x00007ffff7268151 in libbitcoin::chain::history_database::add_output (
    this=this@entry=0x7fffffffe170, key=..., outpoint=..., 
    output_height=output_height@entry=337460, value=value@entry=19296)
    at src/database/history_database.cpp:80
#4  0x00007ffff72628c9 in libbitcoin::chain::db_interface::push_outputs (
    this=this@entry=0x7fffffffe028, tx_hash=..., 
    block_height=block_height@entry=337460, outputs=...)
    at src/db_interface.cpp:211
#5  0x00007ffff7262ba5 in libbitcoin::chain::db_interface::push (
    this=0x7fffffffe028, block=...) at src/db_interface.cpp:119
#6  0x00007ffff7260623 in libbitcoin::chain::organizer::replace_chain (
    this=this@entry=0x6c48c8, fork_index=337459, orphan_chain=...)
    at src/organizer.cpp:222
#7  0x00007ffff7260869 in libbitcoin::chain::organizer::process (
    this=this@entry=0x6c48c8, process_block=...) at src/organizer.cpp:171
#8  0x00007ffff72609d7 in libbitcoin::chain::organizer::start (this=0x6c48c8)
    at src/organizer.cpp:159
#9  0x00007ffff726e074 in libbitcoin::chain::blockchain_impl::do_store(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>) (this=0x7fffffffdfd0, block=..., handle_store=...)
    at src/impl/blockchain_impl.cpp:142
#10 0x00007ffff7270ff0 in operator()<libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>&, void> (
    __object=0x7fffffffdfd0, this=0x7fffebffe120)
    at /usr/include/c++/4.8/functional:601
#11 __call<void, 0ul, 1ul, 2ul> (__args=<optimized out>, this=0x7fffebffe120)
    at /usr/include/c++/4.8/functional:1296
#12 operator()<, void> (this=0x7fffebffe120)
    at /usr/include/c++/4.8/functional:1355
#13 __call<void> (__args=<optimized out>, this=0x7fffebffe120)
    at /usr/include/c++/4.8/functional:1296
#14 operator()<, void> (this=0x7fffebffe120)
    at /usr/include/c++/4.8/functional:1355
#15 asio_handler_invoke<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#16 boost_asio_handler_invoke_helpers::invoke<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >(std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> &, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> &) (function=..., context=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#17 0x00007ffff7277550 in boost::asio::detail::strand_service::dispatch<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> >(boost::asio::detail::strand_service::strand_impl*&, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>&) (this=0x6b7990, 
---Type <return> to continue, or q <return> to quit---
    impl=@0x7fffebffe570: 0x6b8000, handler=...)
    at /usr/include/boost/asio/detail/impl/strand_service.hpp:62
#18 0x00007ffff7277927 in dispatch<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>&> (handler=..., this=0x7fffebffe568)
    at /usr/include/boost/asio/strand.hpp:155
#19 operator() (this=0x7fffebffe568)
    at /usr/include/boost/asio/detail/wrapped_handler.hpp:76
#20 operator() (this=0x7fffebffe4c0)
    at /usr/include/boost/asio/detail/wrapped_handler.hpp:191
#21 asio_handler_invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:64
#22 invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (context=..., function=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#23 asio_handler_invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (
    this_handler=<optimized out>, function=...)
    at /usr/include/boost/asio/detail/wrapped_handler.hpp:275
#24 invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >, boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, li---Type <return> to continue, or q <return> to quit---
bbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > > (
    context=..., function=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#25 boost::asio::detail::completion_handler<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=<optimized out>, 
    base=base@entry=0x7fea246979a0)
    at /usr/include/boost/asio/detail/completion_handler.hpp:68
#26 0x00007ffff7277d43 in boost::asio::detail::strand_service::dispatch<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> > >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> >&) (this=0x6b7990, 
    impl=@0x7fffebffe918: 0x6b8000, handler=...)
    at /usr/include/boost/asio/detail/impl/strand_service.hpp:88
#27 0x00007ffff7277fcc in dispatch<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > > (
    handler=<unknown type in /usr/local/lib/libbitcoin-blockchain.so.0, CU 0x72e9ef, DIE 0x7fbd0d>, this=0x7fffebffe910)
    at /usr/include/boost/asio/strand.hpp:155
#28 asio_handler_invoke<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running> (
    this_handler=0x7fffebffe910, function=...)
    at /usr/include/boost/asio/detail/wrapped_handler.hpp:232
#29 invoke<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_typ---Type <return> to continue, or q <return> to quit---
e, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running> > (context=..., function=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#30 boost::asio::detail::completion_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (
    owner=<optimized out>, base=<optimized out>)
    at /usr/include/boost/asio/detail/completion_handler.hpp:68
#31 0x00007ffff6fb794f in complete (bytes_transferred=<optimized out>, ec=..., 
    owner=..., this=0x7fea45b28340)
    at /usr/include/boost/asio/detail/task_io_service_operation.hpp:37
#32 do_run_one (ec=..., this_thread=..., lock=..., this=0x6a2290)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:384
#33 boost::asio::detail::task_io_service::run (this=0x6a2290, ec=...)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:153
#34 0x00007ffff6fe5487 in run (this=0x7fffffffdd80)
    at /usr/include/boost/asio/impl/io_service.ipp:59
#35 operator() (__closure=<optimized out>) at src/utility/threadpool.cpp:52
#36 _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.8/functional:1732
#37 operator() (this=<optimized out>) at /usr/include/c++/4.8/functional:1720
#38 std::thread::_Impl<std::_Bind_simple<libbitcoin::threadpool::spawn_once()::__lambda0()> >::_M_run(void) (this=<optimized out>)
    at /usr/include/c++/4.8/thread:115
#39 0x00007ffff60d9bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#40 0x00007ffff6cc3182 in start_thread (arg=0x7fffebfff700)
    at pthread_create.c:312
#41 0x00007ffff5b4700d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
I can organize ssh access to the box if this would help.

**Comment by evoskuil** [comment] 2015-02-17 09:32
Did you see https://github.com/libbitcoin/libbitcoin-server/issues/42?

**Comment by evoskuil** [comment] 2015-02-17 09:38
I don't believe you are looking at an infinite loop. The stack trace appears to indicate the exact same issue that we're seeing in the Windows build (and likely in the others). The cause of the problem is understood however the resolution is not yet straightforward as we can't yet be sure of the breadth of the problem, as there is a similar design across the various indices.

**Comment by swansontec** [comment] 2015-02-17 20:40
The process did get killed a few times, which might have been #42, but it was never permanent. Restarting the server would continue syncing as before. This is the first time having the blockchain sync completely stall. We are pretty close to the end, too (height > 330000).

**Comment by evoskuil** [comment] 2015-02-17 21:17
Yes, this is consistent with what we and others are seeing. You may be able to get fully sync'd and run queries, but I would not trust the indexing.

**Comment by evoskuil** [comment] 2015-02-27 03:50
This appears to have been resolved by https://github.com/libbitcoin/libbitcoin-blockchain/commit/081472609da207d07f9f5e2c14af4094018ca9fe

**Closed by evoskuil** 2015-02-27 03:50 UTC
Labels: duplicate

**Comment by swansontec** [comment] 2015-02-28 06:15
I've re-built the server, and it seems to be syncing OK now. It's up to 180000 blocks, and hasn't gotten stuck yet.

**Comment by evoskuil** [comment] 2015-02-28 07:03
Cool, is the problem from issue #50 in the older build then?
