### ISSUE TITLE
Server does not respond to fetch_history2 when using cert

### ISSUE THREAD

**Issue by hoffmabc** [libbitcoin/libbitcoin-server#175] opened 2016-04-06 23:22 UTC
We are noticing on our OpenBazaar libbitcoin nodes that they've seemed to stop responding to fetch history calls even they show in the requests log. They also respond to fetch height as well.

**Comment by evoskuil** [comment] 2016-04-06 23:26
Does fetch-history work via bx?

**Comment by hoffmabc** [comment] 2016-04-06 23:45
No

**Comment by evoskuil** [comment] 2016-04-06 23:55
Glad to help but need more information.

- Can you post or send me a log covering the activity?
- Is the endpoint public, and if so can you give me that and a reproducing address?
- Is the server not responding at all, or is it an empty response?
- Is the history height configured to zero?
- Is it happening on more than one server?
- Have you restarted the server?

**Comment by hoffmabc** [comment] 2016-04-07 00:00
I'll get you the log shortly and give you the connect info. It's not responding at all for the fetch_history2. Height is 0. It's happening on more than one server. We did not reboot the whole VPS.

**Comment by evoskuil** [comment] 2016-04-07 02:20
Were these requests working on the same server but then stopped while it was running?

If `bx fetch-history` is not getting a response it implies an issue with `address.fetch_history` (as well as `address.fetch_history2`). libbitcoin-client doesn't expose call to `address.fetch_history2` so is it safe to assume you are using a custom client implementation?

**Comment by hoffmabc** [comment] 2016-04-07 03:53
We are using curve keys so it's below.

libbitcoin3.openbazaar.org
pco)6}^g!]5b7#byrx>[=MCI#W?DCF}K3FoS6nTu

**Comment by hoffmabc** [comment] 2016-04-07 03:53
Yeah we're using the python client.

**Comment by evoskuil** [comment] 2016-04-07 04:14
port: 9091?

Also:
> Were these requests working on the same server but then stopped while it was running?
> Are you getting a timeout?

**Comment by hoffmabc** [comment] 2016-04-07 04:16
yes port 9091. so just for shits and giggles I turned off encryption on that node and it works great. with the curve stuff turned on it's a no go.

**Comment by evoskuil** [comment] 2016-04-07 04:17
So it's intermittent, as this was working earlier. Sounds like the problem you identified earlier.

**Comment by hoffmabc** [comment] 2016-04-07 04:18
This one is a little different though. It seems to show in the logs as responding to the request (i.e. it shows fetch_history2 coming in and responding) but it never comes back to bx or the python client.

**Comment by evoskuil** [comment] 2016-04-07 04:19
OK, is this a priority for you or can you live without the server cert for a while?

**Comment by hoffmabc** [comment] 2016-04-07 04:21
We will have to disable encrypted libbitcoin connections for the time being which is a security threat but if it resolves the issues our software is having in the meantime we will probably resort to doing that. Do you have thoughts on what it might be?

**Comment by evoskuil** [comment] 2016-04-07 04:24
I don't know, I haven't spent much time in this code. Do you know exactly what versions (or builds) of `libzmq` and `czmq` you are using?

Given the system is trustless, why would it be important that the client-server connection be encrypted?

**Comment by hoffmabc** [comment] 2016-04-07 04:27
I can get you that info.

Well it would be nice to know that the results weren't tampered by anyone in the middle on the way to my OpenBazaar node. I may not trust the end server but at least I know it originated from that node. Also if you're running your own trusted node somewhere it would be hugely important.

**Comment by evoskuil** [comment] 2016-04-07 04:37
> I may not trust the end server but at least I know it originated from that node.
If you don't trust the server then you can't say anything about its response. The key may be stolen or otherwise obtained. Given you are running a public node with a server cert, this is the scenario I assume you are operating under.

>Also if you're running your own trusted node somewhere it would be hugely important.
Yes, this is the intended scenario. Encryption is intended for communication between trusted systems, as where the client and server are both under the physical control of single party, as in a data center or between a wallet and a remote server owned by the wallet owner. I wasn't sure if you had this scenario.

In any case, we should certainly be able to resolve the issue once it can be reproduced locally.

**Comment by hoffmabc** [comment] 2016-04-07 04:38
Ok that would be fantastic and I'll get you the versions on those libs. Thanks for the help.

**Comment by evoskuil** [comment] 2016-04-07 05:53
Do you have access to your console output during the request?

**Comment by evoskuil** [comment] 2016-04-07 11:24
See update: https://github.com/libbitcoin/libbitcoin-server/issues/168

**Comment by evoskuil** [comment] 2016-04-08 21:27
I'm waiting on an analysis of the repro that I created in https://github.com/libbitcoin/libbitcoin-server/issues/168. This may not be the same issue that you are encountering here (as indicated by the log entries) but I hit this 100% of the time, so it must be resolved first.

**Comment by evoskuil** [comment] 2016-05-02 08:26
@hoffmabc Am I correct in assuming that in this scenario you are using a server cert and no client cert? IOW you are providing the server public key to the client but the client is not loading its own identity cert?

**Comment by evoskuil** [comment] 2016-05-02 13:55
Resolved in version2 (pending in master).

**Closed by evoskuil** 2016-05-02 13:55 UTC
Labels: bug
