### ISSUE TITLE
Segfault when starting server

### ISSUE THREAD

**Issue by swansontec** [libbitcoin/libbitcoin-server#98] opened 2015-07-09 00:04 UTC
Things were running smoothly, downloading blocks until height 212579, when the server segfaulted. It now segfaults on every startup.

```
#0  libbitcoin::satoshi_load<unsigned char*, false> (first=0x0, last=last@entry=0x0, packet=...)
    at /usr/local/include/bitcoin/bitcoin/impl/serialize/block.ipp:144
#1  0x00007ffff67e47f4 in deserialize<unsigned char*> (first=<optimized out>) at src/database/block_database.cpp:49
#2  libbitcoin::chain::block_result::header (this=this@entry=0x7ffff0a51f20) at src/database/block_database.cpp:66
#3  0x00007ffff6804a1c in libbitcoin::chain::validate_block_impl::fetch_block (this=<optimized out>, fetch_height=<optimized out>)
    at src/implementation/validate_block_impl.cpp:52
#4  0x00007ffff68048b8 in libbitcoin::chain::validate_block_impl::previous_block_bits (this=<optimized out>)
    at src/implementation/validate_block_impl.cpp:58
#5  0x00007ffff67d8e2a in libbitcoin::chain::validate_block::work_required (this=0x7ffff0a52080) at src/validate_block.cpp:276
#6  0x00007ffff67d913b in libbitcoin::chain::validate_block::accept_block (this=this@entry=0x7ffff0a52080)
    at src/validate_block.cpp:210
#7  0x00007ffff68040f8 in libbitcoin::chain::organizer_impl::verify (this=<optimized out>, fork_index=212580, 
    orphan_chain=std::vector of length 1, capacity 1 = {...}, orphan_index=0) at src/implementation/organizer_impl.cpp:51
#8  0x00007ffff67cc0d1 in libbitcoin::chain::organizer::replace_chain (this=this@entry=0x7fffffffd600, fork_index=212580, 
    orphan_chain=std::vector of length 1, capacity 1 = {...}) at src/organizer.cpp:77
#9  0x00007ffff67ccae0 in libbitcoin::chain::organizer::process (this=this@entry=0x7fffffffd600, 
    process_block=std::shared_ptr (count 5, weak 0) 0x7ff86c004600) at src/organizer.cpp:64
#10 0x00007ffff67cce4e in libbitcoin::chain::organizer::start (this=this@entry=0x7fffffffd600) at src/organizer.cpp:50
#11 0x00007ffff67fff04 in libbitcoin::chain::blockchain_impl::do_store(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>) (this=0x7fffffffd260, block=..., handle_store=...)
    at src/implementation/blockchain_impl.cpp:154
#12 0x00007ffff68036c3 in operator()<libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>&, void> (__object=0x7fffffffd260, this=0x7ffff0a52600) at /usr/include/c++/4.9/functional:569
#13 __call<void, 0ul, 1ul, 2ul> (__args=<optimized out>, this=0x7ffff0a52600) at /usr/include/c++/4.9/functional:1264
#14 operator()<, void> (this=0x7ffff0a52600) at /usr/include/c++/4.9/functional:1323
#15 __call<void> (__args=<optimized out>, this=0x7ffff0a52600) at /usr/include/c++/4.9/functional:1264
#16 operator()<, void> (this=0x7ffff0a52600) at /usr/include/c++/4.9/functional:1323
#17 asio_handler_invoke<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (function=...)
    at /usr/local/include/boost/asio/handler_invoke_hook.hpp:69
#18 invoke<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (context=..., 
    function=...) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#19 boost::asio::detail::strand_service::dispatch<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> >(boost::asio::detail::strand_service::strand_impl*&, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>&) (this=<optimized out>, impl=@0x7ffff0a52760: 0x6253d0, 
    handler=...) at /usr/local/include/boost/asio/detail/impl/strand_service.hpp:62
#20 0x00007ffff6803a11 in dispatch<std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (
    handler=<unknown type in /usr/local/lib/libbitcoin-blockchain.so.0, CU 0x401151, DIE 0x4854f8>, this=0x7ffff0a52758)
    at /usr/local/include/boost/asio/strand.hpp:158
#21 operator() (this=0x7ffff0a52758) at /usr/local/include/boost/asio/detail/wrapped_handler.hpp:76
#22 operator() (this=0x7ffff0a526b0) at /usr/local/include/boost/asio/detail/wrapped_handler.hpp:191
#23 asio_handler_invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > > (function=...) at /usr/local/include/boost/asio/handler_invoke_hook.hpp:69
#24 invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (context=..., function=...)
    at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#25 asio_handler_invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > (this_handler=<optimized out>, 
    function=...) at /usr/local/include/boost/asio/detail/wrapped_handler.hpp:275
#26 invoke<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> >, boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > > (
    context=..., function=...) at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#27 boost::asio::detail::completion_handler<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=0x60d750, base=base@entry=0x7ff86c0045f0)
---Type <return> to continue, or q <return> to quit---
    at /usr/local/include/boost/asio/detail/completion_handler.hpp:68
#28 0x00007ffff6803d19 in boost::asio::detail::strand_service::dispatch<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> > >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()> >&) (
    this=0x624d60, impl=@0x7ffff0a52998: 0x6253d0, handler=...) at /usr/local/include/boost/asio/detail/impl/strand_service.hpp:88
#29 0x00007ffff6803f79 in dispatch<boost::asio::detail::rewrapped_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()> > > (handler=<unknown type in /usr/local/lib/libbitcoin-blockchain.so.0, CU 0x401151, DIE 0x48721f>, 
    this=0x7ffff0a52990) at /usr/local/include/boost/asio/strand.hpp:158
#30 asio_handler_invoke<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running> (this_handler=0x7ffff0a52990, function=...)
    at /usr/local/include/boost/asio/detail/wrapped_handler.hpp:232
#31 invoke<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running>, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(const libbitcoin::block_type&, std::function<void(const std::error_code&, libbitcoin::block_info)>)>(libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void(const std::error_code&, libbitcoin::block_info)>)>()>, boost::asio::detail::is_continuation_if_running> > (context=..., function=...)
    at /usr/local/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#32 boost::asio::detail::completion_handler<boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Bind<std::_Mem_fn<void (libbitcoin::chain::blockchain_impl::*)(libbitcoin::block_type const&, std::function<void (std::error_code const&, libbitcoin::block_info)>)> (libbitcoin::chain::blockchain_impl*, libbitcoin::block_type, std::function<void (std::error_code const&, libbitcoin::block_info)>)> ()>, boost::asio::detail::is_continuation_if_running> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) (owner=<optimized out>, 
    base=<optimized out>) at /usr/local/include/boost/asio/detail/completion_handler.hpp:68
#33 0x00007ffff78cef58 in complete (bytes_transferred=<optimized out>, ec=..., owner=..., this=<optimized out>)
    at /usr/local/include/boost/asio/detail/task_io_service_operation.hpp:38
#34 do_run_one (ec=..., this_thread=..., lock=..., this=<optimized out>)
    at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:384
#35 run (ec=..., this=<optimized out>) at /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:153
#36 run (this=<optimized out>) at /usr/local/include/boost/asio/impl/io_service.ipp:59
#37 operator() (__closure=<optimized out>, __closure=<optimized out>) at src/utility/threadpool.cpp:56
#38 _M_invoke<> (this=<optimized out>) at /usr/include/c++/4.9/functional:1700
#39 operator() (this=<optimized out>) at /usr/include/c++/4.9/functional:1688
#40 std::thread::_Impl<std::_Bind_simple<libbitcoin::threadpool::spawn_once(libbitcoin::thread_priority)::<lambda()>()> >::_M_run(void) (this=<optimized out>) at /usr/include/c++/4.9/thread:115
#41 0x00007ffff7327e30 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#42 0x00007ffff5e046aa in start_thread (arg=0x7ffff0a53700) at pthread_create.c:333
#43 0x00007ffff6d93eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by evoskuil** [comment] 2015-07-10 20:09
The only explanation for this that I can postulate is the existence of invalid data in the block database. The important question is whether this occurred due to a bug or due to a disk fault. Since Nobody has reported this and I just synced without seeing it, it doesn't appear to be a related to have resulted from some unique blockchain data, although given the complexity of interactions, it's impossible to rule that out.

I suggest running this again to see if it reproduces before we go any further with it.

**Comment by evoskuil** [comment] 2015-07-11 15:57
I recently reproduced a similar behavior on OSX. This followed a hard shutdown of the database as the consequence of excessive memory consumption (open issue). Resolved by deleting the blockchain directory and restarting.

**Comment by evoskuil** [comment] 2015-07-26 08:30
See also bottom of: https://github.com/libbitcoin/libbitcoin-server/issues/36#issuecomment-124949966

**Comment by evoskuil** [comment] 2015-07-31 17:12
If you rebuild with latest you should be able to see if it is [this issue](https://github.com/libbitcoin/libbitcoin-blockchain/issues/96).

**Closed** 2015-10-15 03:48 UTC
Labels: bug
