### ISSUE TITLE
[master] initial block download inoperative

### ISSUE THREAD

**Issue by thecodefactory** [libbitcoin/libbitcoin-server#256] opened 2016-10-10 03:56 UTC
master is a moving target, but at the moment, it doesn't sync at all and I wanted to be sure it's a known regression.  Just tried a fresh install from server (commit hash 5328a8ac8f06226311f43b0eaaf90ed9d74e5eda) and running bs doesn't sync at all, but runs indefinitely.  error.log has many entries of the form "... WARNING [node] Failure merging headers from [...]"

**Comment by evoskuil** [comment] 2016-10-10 05:14
Yes, thanks for posting. I am aware. It is a regression due to some work I did while traveling. I'm at Scaling Bitcoin and haven't had a chance to clean it up. There is a deeper issue that needs to be resolved, which I should be able to resolve in a couple of days.

You may be able to run well from genesis with full. validation by reducing checkpoints to just block zero.

**Comment by evoskuil** [comment] 2016-10-21 16:38
This particular issue is resolved, but initial block download is being reworked (for parallel header download).

**Comment by evoskuil** [comment] 2017-02-08 08:53
Iv'e bumped the node task to v3.1.

**Comment by evoskuil** [comment] 2017-02-08 08:53
Closing this server issue as this is a node item.

**Closed by evoskuil** 2017-02-08 08:53 UTC
Labels: enhancement
